### ADJUSTED: Add the RD FOM HPC entrypoint with shared staged training and saving.
const REPO_ROOT = normpath(joinpath(@__DIR__, "..", "..", "..", ".."))
include(joinpath(@__DIR__, "hpc_logging.jl"))
include(joinpath(REPO_ROOT, "Research_Code", "src", "HPC", "Simulations", "FOM_opt_RD_hpc.jl"))
include(joinpath(@__DIR__, "hpc_common.jl"))
include(joinpath(@__DIR__, "Sweeps", "RD_initial_conditions.jl"))

opts = parse_cli(ARGS)
N = get_int(opts, "N", 128)
L = get_float(opts, "L", 1.0)
D1 = get_float(opts, "d1", 2.8e-4)
D2 = get_float(opts, "d2", 5.0e-2)
tfinal = get_float(opts, "tfinal", 2.0)
N_obs = get_int(opts, "N-obs", 10)
h = get_int(opts, "h", 8)
seed = get_int(opts, "seed", 1)
reference_dt_factor = get_float(opts, "reference-dt-factor", 0.5)
dimension = get_int(opts, "dimension", 2)
boundary_condition = get_string(opts, "boundary-condition", "neumann")
initial_condition = get_string(opts, "initial-condition", "default")
learner = lowercase(get_string(opts, "learner", "nn"))
polynomial_degree = get_int(opts, "polynomial-degree", 3)
etas = get_float_vector(opts, "etas", [5e-3, 1e-3, 1e-4])
iterations = get_int_vector(opts, "iters", [500, 800, 1100])
stage_count = length(etas)
window_T = get_float_vector(opts, "window-T", fill(tfinal, stage_count))
window_N_obs = get_int_vector(opts, "window-N-obs", fill(N_obs, stage_count))
window_start_policy = get_string_vector(opts, "window-start-policy", fill("beginning", stage_count))
batch_size = get_int_vector(opts, "batch-size", fill(1, stage_count))
loss_normalization = get_string(opts, "loss-normalization", "mean")
window_seed = get_int(opts, "window-seed", seed)
β = get_float_tuple(opts, "beta", (0.9, 0.99))
warmup = get_bool(opts, "warmup", true)
save_frequency = get_int(opts, "save-frequency", 10)
print_frequency = get_int(opts, "print-frequency", 10)
run_name = get_string(opts, "run-name", timestamp_run_name("FOM_RD_hpc"))
all(==(stage_count), (length(iterations), length(window_T), length(window_N_obs), length(window_start_policy), length(batch_size))) || error("staged RD schedules must have equal lengths")
assert_run_name_available(run_name)

setup_hpc_runtime()
u₀ = rd_materialize_sweep_initial_condition(initial_condition; N, L, dimension, boundary_condition, seed)
reference = build_rd_reference(; N, L, D1, D2, tfinal, reference_dt_factor, dimension, boundary_condition, u₀)
prepared = prepare_RD_FOM_optimization(; N, L, D1, D2, tspan=reference.tspan, N_obs, dimension=reference.dimension, boundary_condition, u₀=reference.u₀, learner, h, seed, polynomial_degree)
run_params = merge(prepared.run_params, (; D1, D2, reference_dt=reference.Δt, reference_dt_factor, reference_save_count=length(reference.t), initial_condition, hpc_job_id=get(ENV, "SLURM_JOB_ID", "local"), hpc_array_task_id=get(ENV, "SLURM_ARRAY_TASK_ID", ""), variable_window_training=true))
println("  equation = rd\n  run_name = ", run_name, "\n  N = ", N, "\n  L = ", L, "\n  D1 = ", D1, "\n  D2 = ", D2, "\n  tfinal = ", tfinal, "\n  N_obs = ", N_obs, "\n  dimension = ", dimension, "\n  boundary_condition = ", boundary_condition, "\n  learner = ", learner, "\n  polynomial_degree = ", polynomial_degree)
flush(stdout)
output = run_variable_window_RD_FOM_optimization(reference.u_ref, prepared.prob, prepared.p₀; run_params, eta=etas, beta=β, N_iter=iterations, window_T, window_N_obs, window_start_policy, batch_size, loss_normalization, window_seed, validation_N_obs=N_obs, warmup, save_frequency, print_frequency)
save_dir = save_variable_window_RD_FOM_optimization_data(output, run_name)
println("Saved FOM output to: ", save_dir)
println("Final full-trajectory loss: ", output.final_full_trajectory_loss)
